version: '3.9'

services:
  db:
    image: postgres:17.2-alpine3.21
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=agriconnect
  redis:
    image: redis:7.4.1-alpine
    ports:
      - 6379:6379
    