name: test-build-push workflow

on: 
    push: 
        branches: [main]

jobs:
    tester:
        name: Testing code
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: setup node.js latest
              uses: actions/setup-node@v4
              with:
                node-version: 23
            
            - name: install pnpm
              run: npm i pnpm

            - name: install dependecies
              run: pnpm install
            
            - name: Testing Next.js code
              run: pnpm test
    
    # build-and-push:
    #     name: Building docker image and push to docker hub
    #     runs-on: ubuntu-latest
    #     needs: 
    #         - tester
    #     steps:
    #       - name: Docker build push
    #         uses: seepine/action-docker-build-push@v1
    #         with:
    #             registry: docker.io
    #             username: sumit53
    #             password: ${{secrets.DOCKER_PASSWORD}}
    #             platforms: linux/amd64,linux/arm64
    #             tags:   |
    #                 docker.io/sumit53/agriconnect:latest
    #                 docker.io/sumit53/agriconnect:${{github.sha}}